sudo: false
language: node_js
node_js:
  - v5
  - v4
services: mongodb
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env: CXX="g++-4.8" CC="gcc-4.8"
before_script: 
    - npm install bower -g
script: npm run-script test-travis
after_success: cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js && rm -rf ./coverage